version: '3.5'

services:
  db_analyzer:
    container_name: text_analyzer
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    image: postgres:15.6-alpine3.19